### ISSUE TITLE
Any plan to add sh2_dynarec ?

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/yabause#14]
I have my rpi2 up and running, i built yabause libretro and i was able to load some games. The only issue is the speed, but it was predictable since sh2_dynarec with its armv6, armv7 and neon optimization is disabled in yabause-libretro. So is there any plan to add the sh2_dynarec from yabause stand-alone in yabause-libretro ?

**Comment by twinaphex** [comment]
Well, on PC x86/x86_64 the main issue is that the SH2 dynarec is not PIC/PIE-compatible right now. It would first have to be fixed.

**Comment by Enverex** [comment]
A good explanation of the current issue - https://github.com/Yabause/yabause/issues/270

**Comment by barbudreadmon** [comment]
I kinda remember there was a sh2 dynarec for 32X written by @notaz, i wonder if it could help with this issue.

**Comment by twinaphex** [comment]
Would be way too much work to integrate into Yabause, and honestly, making the Ari64 dynarec in Yabause PIC-compatible would be substantially less work. Somebody competent only needs to start looking into this, and it's kinda dispiriting that even mainline Yabause devs are coming up short here. The problems of adopting somebody else's dynarec code without properly understanding it yourself I guess.

**Comment by rcaridade145** [comment]
Yabause team seems to be developing a new jit based on Play! 

https://github.com/Yabause/yabause/blob/master/yabause/src/CMakeLists.txt#L741 .

There is hope :)

**Comment by hooby3dfx** [comment]
To clarify - is the ARM dynarec code PIC compatible?

**Comment by barbudreadmon** [comment]
Is the sh2 dynarec from the yabause port at https://github.com/FCare/yabause/tree/extui-align/yabause/src/sh2_kronos somehow usable ?

Seems to me like it is cross platform and pic compatible.

**Comment by fr500** [comment]
I think a better effort would be to port yaba sanshiro

**Comment by barbudreadmon** [comment]
@fr500 
Well, i couldn't get YabaSanchiro standalone running on my system, and from what i heard and what i see in the sources, i'm not sure it will help a lot with speed on any hardware which is not gles3+arm (my target machine is a nuc-like machine with a pentium @2.56Ghz and an intel gpu).

So i ended up porting @FCare 's port of yabause (it's named kronos if i understood well) by mixing https://github.com/FCare/yabause and https://github.com/libretro/yabause : https://github.com/barbudreadmon/kronos-libretro

This repo is more like a proof of concept since i'm not sure we should keep this separate from upstream (there are very few changes to the codebase, and i did them properly by using `#ifndef __LIBRETRO__` macros) and/or libretro-yabause fork.

The core is still in early stage, i finished it today before going to work, and didn't even get the time to test it on my target machine. On my main machine it seemed to run games fine with the alternate sh2 interpreter.

**Comment by FCare** [comment]
Hi,
Thanks for looking at my sh2_dynarec. 
For the history:
The yaba sanshiro sh2 interpreter is not working for linux x64. I tried first to do a port of this interpreter to the x64 but the games are not booting with this port (available in the sh2_dynarec_devmiyax directory), I still do not know why. So I wrote a new sh2_dynarec, the one you are looking at, in full C. The idea is to auto-generate all the opcode combinatory at compile time. Then during execution, there is only one call, without parameter, for each opcode. Here the idea is to be HW independant, and to not rely on the stack usage for passing parameters. There is a good improvement in terms of CPU load, quite close to the yaba sanshiro one. 
There is one last optimisation that can be done since each call is still using the context as a parameter. The idea would be to duplicate the number of functions, one set for the MSH2, one for the SSH2. But I am not sure it will save a lot of CPU.
An other optimisation missing today is the loop detector.

**Comment by barbudreadmon** [comment]
> The yaba sanshiro sh2 interpreter is not working for linux x64

@FCare That makes it a no-go for me, my target machine is x86_64

As a sidenote i did a PR on YabaSanchiro since i'm also interested in the standalone version (your standalone fork works perfectly on my target machine, this is why i ended up working on it, but i could revert back to your standalone version if the libretro port doesn't run full speed on my target machine after i finish it), it's about controllers, i mentioned you, perhaps you could help with it.

**Comment by FCare** [comment]
@barbudreadmon Same on my side, Yaba is a no-go for my x64 based retro machine... That's why I forked kronos.
Regarding the controllers part, I did nto get totally your point... What is the controller model? In which file did you looked? You are compiling a qt version or the more simple glfw version?

**Comment by rcaridade145** [comment]
@FCare yabause has as far as i can tell somes fixes from yaba sanshiro and some of its own.  

> . The idea would be to duplicate the number of functions, one set for the MSH2, one for the SSH2. But I am not sure it will save a lot of CPU.

Probably not, however it does seem calling for a multithreaded, probably not worth it , attempt :)

Great work @FCare @barbudreadmon

**Comment by barbudreadmon** [comment]
@FCare i'll open an issue about the controller on your repo, we are going off-topic here ;). Also, are you french ? I noticed most issues are in french on your repo.

**Comment by barbudreadmon** [comment]
Cleaning up, this is a duplicate of https://github.com/libretro/yabause/issues/51.

Closing !

**Comment by wn2000** [comment]
I know I'm digging an old and closed issue. But just wonder, the recent work on sh2_dynarec for picodrive done by @irixxxx has been pretty impressive (https://github.com/irixxxx/picodrive now also merged to https://github.com/libretro/picodrive). Do you guys think it's possible to integrate that into yabause?
