### ISSUE TITLE
any support for eepc/arm eepc/xandros and emebed devices with androit

### ISSUE THREAD

**Issue by mckaygerhard** [libretro/yabause#21]
I have not compiled yet, and due this its the only place for close questions about libretro related

still are supported custon linux for https://en.wikipedia.org/wiki/Smartbook that devices?

an for https://en.wikipedia.org/wiki/Netbook recent linux with opengl-es are installable but performance with modern linuxes are very poor (below guindows), some linuxes like DSL, debian sable 6, xandrosos runs with high performance here!

another its the pc's with matrox, voodoo and SIS card GPU thatno support Opengl-es but capable to run saturn games due in guindows are runnig!

**i ask that due i see that this project only retrieves the commits from main repo and does no more!** no value add, only runs behind.. 

so theres any plansto support that **low end hardware**, or custom made linuxes!??

**Comment by barbudreadmon** [comment]
There are 3 flavors of yabause cores : 
- standard yabause with software renderer and interpreter, this one requires a good cpu (above 3Ghz)
- kronos with hardware renderer and cached interpreter, this one has less requirement on cpu (should be ok with a cpu slightly lower than 2.5Ghz) but requires a decent gpu (opengl 3.3+, decent benchmark, and non-intel because opengl on intel is missing a lot of stuff)
- yabasanshiro with hardware renderer (require opengl 3.3+ too) and dynarec for arm/aarch64, it also has a frameskip feature which makes it run pretty well on any middle-end device

Choose the one that performs better on your device, but don't expect to run saturn on devices from last century (matrox ? voodoo ? sis ???), that's simply unrealistic, closing.

**Comment by mckaygerhard** [comment]
> Choose the one that performs better on your device, but don't expect to run saturn on devices from last century (matrox ? voodoo ? sis ???), that's simply unrealistic, closing.

seems simple are **unrealisting your proyect does not make sense.. it's waste time try to use your emulator in a xpensive machine,for that i buy a console in amazon, puf**
