### ISSUE TITLE
Missing core option labels

### ISSUE THREAD

**Issue by Sanaki** [libretro/yabause#269]
As of libretro/RetroArch@fe1f311a35a5c8a56e65aaf5ad7cc55a35e0feae, core options no longer display descriptions and only display the literal value for options rather than the option label. I verified this in both Yabause and Kronos on x86_64 Linux.

**Comment by barbudreadmon** [comment]
I can't test right now, but from what you are telling me, this is a regression in retroarch and should be reported in their repo.

**Comment by Sanaki** [comment]
Thing is, it only applies to these cores that I've seen. It may be worth determining why.

**Comment by jdgleaver** [comment]
Ah, it's this old chestnut: https://github.com/libretro/yabause/blob/d9ef00cf573a86cf6a9ee34ef90e319bbcffd333/yabause/src/libretro/libretro_core_options.h#L345

`(version == 1)` should be `(version >= 1)`

This was fixed in the core option sample files and basically every other core a long time ago - but I guess this repo was overlooked...

**Comment by barbudreadmon** [comment]
@jdgleaver thanks !
