### ISSUE TITLE
[Yabause/YabaSanshiro] Redump disc support?

### ISSUE THREAD

**Issue by telanus** [libretro/yabause#56]
Seems when one run a multi-track redump disc, the core will boot to the music player, but if you mount the disc and rip into a single file it'll work

**Comment by barbudreadmon** [comment]
This repository is now home to 3 emulators, which one are you talking about ?

**Comment by telanus** [comment]
Both the yabasanshiro & yabause, Kronos works with the images

**Comment by barbudreadmon** [comment]
Sorry but thinning the differences between YabaSanshiro and Kronos without the consent of both authors is against my policy (i'll do the porting if they both agree though). There was too much bitching about Kronos being a cheap copy of YabaSanshiro on reddit/twitter, people even got as far as starting rumors about me and @FCare hacking @devmiyax's website because we were jealous some time ago. I was seriously pissed off considering we never had any ill will against YabaSanshiro, and both emulators, apart from their common trunk which is yabause, actually differ a lot (YabaSanshiro's main features are arm/aarch64 SH2 dynarecs and gles3 renderer, it's mostly targeted at mobile devices; Kronos's main features are cross-platform SH2 "cached interpreter", glcore renderer, and stv support, it's mostly targeted at desktop devices).

Sorry for the silly reason but i don't want to see haters and assholes starting other awful rumors, dirtying the work of developpers doing it for free, they are conspirationist with too much imagination.

About porting it to legacy yabause, it might be a good idea to update it first because i think our current version isn't in sync with the latest version. Most likely i'll take a look this week-end.

**Comment by barbudreadmon** [comment]
> but if you mount the disc and rip into a single file it'll work

@telanus on a sidenote, i recommend googling "cdmage", which is a lot better/faster/easier solution to convert whatever iso you have to "single file bin/cue" : 

1. File > Open > select your iso (NB : for multi-track, select the cue file)
2. File > Save As > write the name of your new file
3. Make sure you select MODE1/2352 in the second drop-down
4. Press OK, wait for the process to finish (a few seconds on my computer), and it’s done !

**Comment by FCare** [comment]
Please read this regarding kronos: https://fcare.github.io/

**Comment by Philps** [comment]
I am using IAGL on Kodi 18.2 FireTv Gen2 [armv7]. 

All Files from IAGL are .bin + .cue Files.

While its working fine with Beetle Saturn\mednafen saturn its only booting into music player.

**Comment by bparker06** [comment]
@barbudreadmon In all fairness, trolls will continue doing their thing for at least as long as you seem to be bothered by their actions, that's just more fuel for the fire.

Best thing to do would be to ignore it IMO.

**Comment by telanus** [comment]
>  In all fairness, trolls will continue doing their thing

So is asking for support of a known dumping technique now trolling?

**Comment by barbudreadmon** [comment]
He meant the trolling on reddit/twitter, not your request.

**Comment by barbudreadmon** [comment]
@telanus I ended up porting support for unzipped TAO dumps to both yabause & yabasanshiro cores.
Having to convert my redump isos to DAO every time i had to work on those cores was really annoying.
I won't port support for zipped bin/cue dumps though because of all the controversy about it (it's kinda slow to load and store the iso in ram).
Closing !
